#!/usr/bin/python

import sys
from opencontrail_config.config_shell import *

default_client_args = [
    ('--auth-username', 'admin'),
    ('--auth-password', 'contrail123'),
    ('--auth-tenant', 'admin'),
    ('--auth-region', 'RegionOne'),
    ('--auth-server', '127.0.0.1'),
    ('--api-server', '127.0.0.1'),
    ('--tenant', 'demo')]

if __name__ == '__main__':
    for arg in default_client_args:
        if not arg[0] in sys.argv:
            sys.argv.insert(1, arg[0])
            sys.argv.insert(2, arg[1])
    ConfigShell().main()

