res_type = {u'AclEntriesType': {'member': {u'acl_rule': {'sequence': True,
                                              'type': u'AclRuleType'},
                                u'dynamic': {'sequence': False,
                                             'type': u'xsd:boolean'}},
                     'name': u'AclEntriesType'},
 u'AclRuleType': {'member': {u'action_list': {'sequence': False,
                                              'type': u'ActionListType'},
                             u'match_condition': {'sequence': False,
                                                  'type': u'MatchConditionType'},
                             u'rule_uuid': {'sequence': False,
                                            'type': u'xsd:string'}},
                  'name': u'AclRuleType'},
 u'ActionListType': {'member': {u'apply_service': {'sequence': True,
                                                   'type': u'xsd:string'},
                                u'assign_routing_instance': {'sequence': False,
                                                             'type': u'xsd:string'},
                                u'gateway_name': {'sequence': False,
                                                  'type': u'xsd:string'},
                                u'mirror_to': {'sequence': False,
                                               'type': u'MirrorActionType'},
                                u'simple_action': {'sequence': False,
                                                   'type': u'xsd:string'}},
                     'name': u'ActionListType'},
 u'AddressType': {'member': {u'network_policy': {'sequence': False,
                                                 'type': u'xsd:string'},
                             u'security_group': {'sequence': False,
                                                 'type': u'xsd:string'},
                             u'subnet': {'sequence': False,
                                         'type': u'SubnetType'},
                             u'virtual_network': {'sequence': False,
                                                  'type': u'xsd:string'}},
                  'name': u'AddressType'},
 u'AllocationPoolType': {'member': {u'end': {'sequence': False,
                                             'type': u'xsd:string'},
                                    u'start': {'sequence': False,
                                               'type': u'xsd:string'}},
                         'name': u'AllocationPoolType'},
 u'AllowedAddressPair': {'member': {u'address_mode': {'sequence': False,
                                                      'type': u'xsd:string'},
                                    u'ip': {'sequence': False,
                                            'type': u'SubnetType'},
                                    u'mac': {'sequence': False,
                                             'type': u'xsd:string'}},
                         'name': u'AllowedAddressPair'},
 u'AllowedAddressPairs': {'member': {u'allowed_address_pair': {'sequence': True,
                                                               'type': u'AllowedAddressPair'}},
                          'name': u'AllowedAddressPairs'},
 u'ApiAccessListType': {'member': {u'api_access': {'sequence': True,
                                                   'type': u'ApiAccessType'}},
                        'name': u'ApiAccessListType'},
 u'ApiAccessType': {'member': {u'api_name': {'sequence': False,
                                             'type': u'xsd:string'},
                               u'permissions': {'sequence': False,
                                                'type': u'PermType'}},
                    'name': u'ApiAccessType'},
 u'DhcpOptionType': {'member': {u'dhcp_option_name': {'sequence': False,
                                                      'type': u'xsd:string'},
                                u'dhcp_option_value': {'sequence': False,
                                                       'type': u'xsd:string'},
                                u'dhcp_option_value_bytes': {'sequence': False,
                                                             'type': u'xsd:string'}},
                     'name': u'DhcpOptionType'},
 u'DhcpOptionsListType': {'member': {u'dhcp_option': {'sequence': True,
                                                      'type': u'DhcpOptionType'}},
                          'name': u'DhcpOptionsListType'},
 u'DomainLimitsType': {'member': {u'project_limit': {'sequence': False,
                                                     'type': u'xsd:integer'},
                                  u'security_group_limit': {'sequence': False,
                                                            'type': u'xsd:integer'},
                                  u'virtual_network_limit': {'sequence': False,
                                                             'type': u'xsd:integer'}},
                       'name': u'DomainLimitsType'},
 u'EncapsulationPrioritiesType': {'member': {u'encapsulation': {'sequence': True,
                                                                'type': u'xsd:string'}},
                                  'name': u'EncapsulationPrioritiesType'},
 u'FloatingIpPoolType': {'member': {u'subnet': {'sequence': True,
                                                'type': u'SubnetType'}},
                         'name': u'FloatingIpPoolType'},
 u'IdPermsType': {'member': {u'created': {'sequence': False,
                                          'type': u'xsd:dateTime'},
                             u'creator': {'sequence': False,
                                          'type': u'xsd:string'},
                             u'description': {'sequence': False,
                                              'type': u'xsd:string'},
                             u'enable': {'sequence': False,
                                         'type': u'xsd:boolean'},
                             u'last_modified': {'sequence': False,
                                                'type': u'xsd:dateTime'},
                             u'permissions': {'sequence': False,
                                              'type': u'PermType'},
                             u'user_visible': {'sequence': False,
                                               'type': u'xsd:boolean'},
                             u'uuid': {'sequence': False,
                                       'type': u'UuidType'}},
                  'name': u'IdPermsType'},
 u'InterfaceMirrorType': {'member': {u'mirror_to': {'sequence': False,
                                                    'type': u'MirrorActionType'},
                                     u'traffic_direction': {'sequence': False,
                                                            'type': u'xsd:string'}},
                          'name': u'InterfaceMirrorType'},
 u'IpAddressesType': {'member': {u'ip_address': {'sequence': True,
                                                 'type': u'xsd:string'}},
                      'name': u'IpAddressesType'},
 u'IpamDnsAddressType': {'member': {u'tenant_dns_server_address': {'sequence': False,
                                                                   'type': u'IpAddressesType'},
                                    u'virtual_dns_server_name': {'sequence': False,
                                                                 'type': u'xsd:string'}},
                         'name': u'IpamDnsAddressType'},
 u'IpamSubnetType': {'member': {u'addr_from_start': {'sequence': False,
                                                     'type': u'xsd:boolean'},
                                u'allocation_pools': {'sequence': True,
                                                      'type': u'AllocationPoolType'},
                                u'default_gateway': {'sequence': False,
                                                     'type': u'xsd:string'},
                                u'dhcp_option_list': {'sequence': False,
                                                      'type': u'DhcpOptionsListType'},
                                u'dns_nameservers': {'sequence': True,
                                                     'type': u'xsd:string'},
                                u'dns_server_address': {'sequence': False,
                                                        'type': u'xsd:string'},
                                u'enable_dhcp': {'sequence': False,
                                                 'type': u'xsd:boolean'},
                                u'host_routes': {'sequence': False,
                                                 'type': u'RouteTableType'},
                                u'subnet': {'sequence': False,
                                            'type': u'SubnetType'},
                                u'subnet_name': {'sequence': False,
                                                 'type': u'xsd:string'},
                                u'subnet_uuid': {'sequence': False,
                                                 'type': u'xsd:string'}},
                     'name': u'IpamSubnetType'},
 u'IpamType': {'member': {u'cidr_block': {'sequence': False,
                                          'type': u'SubnetType'},
                          u'dhcp_option_list': {'sequence': False,
                                                'type': u'DhcpOptionsListType'},
                          u'host_routes': {'sequence': False,
                                           'type': u'RouteTableType'},
                          u'ipam_dns_method': {'sequence': False,
                                               'type': u'xsd:string'},
                          u'ipam_dns_server': {'sequence': False,
                                               'type': u'IpamDnsAddressType'},
                          u'ipam_method': {'sequence': False,
                                           'type': u'xsd:string'}},
               'name': u'IpamType'},
 u'JunosServicePorts': {'member': {u'service_port': {'sequence': True,
                                                     'type': u'xsd:string'}},
                        'name': u'JunosServicePorts'},
 u'KeyValuePair': {'member': {u'key': {'sequence': False,
                                       'type': u'xsd:string'},
                              u'value': {'sequence': False,
                                         'type': u'xsd:string'}},
                   'name': u'KeyValuePair'},
 u'KeyValuePairs': {'member': {u'key_value_pair': {'sequence': True,
                                                   'type': u'KeyValuePair'}},
                    'name': u'KeyValuePairs'},
 u'LinklocalServiceEntryType': {'member': {u'ip_fabric_DNS_service_name': {'sequence': False,
                                                                           'type': u'xsd:string'},
                                           u'ip_fabric_service_ip': {'sequence': True,
                                                                     'type': u'xsd:string'},
                                           u'ip_fabric_service_port': {'sequence': False,
                                                                       'type': u'xsd:integer'},
                                           u'linklocal_service_ip': {'sequence': False,
                                                                     'type': u'xsd:string'},
                                           u'linklocal_service_name': {'sequence': False,
                                                                       'type': u'xsd:string'},
                                           u'linklocal_service_port': {'sequence': False,
                                                                       'type': u'xsd:integer'}},
                                'name': u'LinklocalServiceEntryType'},
 u'LinklocalServicesTypes': {'member': {u'linklocal_service_entry': {'sequence': True,
                                                                     'type': u'LinklocalServiceEntryType'}},
                             'name': u'LinklocalServicesTypes'},
 u'LoadbalancerHealthmonitorType': {'member': {u'admin_state': {'sequence': False,
                                                                'type': u'xsd:boolean'},
                                               u'delay': {'sequence': False,
                                                          'type': u'xsd:integer'},
                                               u'expected_codes': {'sequence': False,
                                                                   'type': u'xsd:string'},
                                               u'http_method': {'sequence': False,
                                                                'type': u'xsd:string'},
                                               u'max_retries': {'sequence': False,
                                                                'type': u'xsd:integer'},
                                               u'monitor_type': {'sequence': False,
                                                                 'type': u'xsd:string'},
                                               u'timeout': {'sequence': False,
                                                            'type': u'xsd:integer'},
                                               u'url_path': {'sequence': False,
                                                             'type': u'xsd:string'}},
                                    'name': u'LoadbalancerHealthmonitorType'},
 u'LoadbalancerListenerType': {'member': {u'admin_state': {'sequence': False,
                                                           'type': u'xsd:boolean'},
                                          u'protocol': {'sequence': False,
                                                        'type': u'xsd:string'},
                                          u'protocol_port': {'sequence': False,
                                                             'type': u'xsd:integer'}},
                               'name': u'LoadbalancerListenerType'},
 u'LoadbalancerMemberType': {'member': {u'address': {'sequence': False,
                                                     'type': u'xsd:string'},
                                        u'admin_state': {'sequence': False,
                                                         'type': u'xsd:boolean'},
                                        u'protocol_port': {'sequence': False,
                                                           'type': u'xsd:integer'},
                                        u'status': {'sequence': False,
                                                    'type': u'xsd:string'},
                                        u'status_description': {'sequence': False,
                                                                'type': u'xsd:string'},
                                        u'weight': {'sequence': False,
                                                    'type': u'xsd:integer'}},
                             'name': u'LoadbalancerMemberType'},
 u'LoadbalancerPoolType': {'member': {u'admin_state': {'sequence': False,
                                                       'type': u'xsd:boolean'},
                                      u'loadbalancer_method': {'sequence': False,
                                                               'type': u'xsd:string'},
                                      u'protocol': {'sequence': False,
                                                    'type': u'xsd:string'},
                                      u'session_persistence': {'sequence': False,
                                                               'type': u'xsd:string'},
                                      u'status': {'sequence': False,
                                                  'type': u'xsd:string'},
                                      u'status_description': {'sequence': False,
                                                              'type': u'xsd:string'},
                                      u'subnet_id': {'sequence': False,
                                                     'type': u'xsd:string'}},
                           'name': u'LoadbalancerPoolType'},
 u'LoadbalancerType': {'member': {u'admin_state': {'sequence': False,
                                                   'type': u'xsd:boolean'},
                                  u'operating_status': {'sequence': False,
                                                        'type': u'xsd:string'},
                                  u'provisioning_status': {'sequence': False,
                                                           'type': u'xsd:string'},
                                  u'status': {'sequence': False,
                                              'type': u'xsd:string'},
                                  u'vip_address': {'sequence': False,
                                                   'type': u'xsd:string'},
                                  u'vip_subnet_id': {'sequence': False,
                                                     'type': u'xsd:string'}},
                       'name': u'LoadbalancerType'},
 u'MacAddressesType': {'member': {u'mac_address': {'sequence': True,
                                                   'type': u'xsd:string'}},
                       'name': u'MacAddressesType'},
 u'MatchConditionType': {'member': {u'dst_address': {'sequence': False,
                                                     'type': u'AddressType'},
                                    u'dst_port': {'sequence': False,
                                                  'type': u'PortType'},
                                    u'ethertype': {'sequence': False,
                                                   'type': u'xsd:string'},
                                    u'protocol': {'sequence': False,
                                                  'type': u'xsd:string'},
                                    u'src_address': {'sequence': False,
                                                     'type': u'AddressType'},
                                    u'src_port': {'sequence': False,
                                                  'type': u'PortType'}},
                         'name': u'MatchConditionType'},
 u'MirrorActionType': {'member': {u'analyzer_ip_address': {'sequence': False,
                                                           'type': u'xsd:string'},
                                  u'analyzer_name': {'sequence': False,
                                                     'type': u'xsd:string'},
                                  u'encapsulation': {'sequence': False,
                                                     'type': u'xsd:string'},
                                  u'routing_instance': {'sequence': False,
                                                        'type': u'xsd:string'},
                                  u'udp_port': {'sequence': False,
                                                'type': u'xsd:integer'}},
                       'name': u'MirrorActionType'},
 u'PermType': {'member': {u'group': {'sequence': False,
                                     'type': u'xsd:string'},
                          u'group_access': {'sequence': False,
                                            'type': u'xsd:integer'},
                          u'other_access': {'sequence': False,
                                            'type': u'xsd:integer'},
                          u'owner': {'sequence': False,
                                     'type': u'xsd:string'},
                          u'owner_access': {'sequence': False,
                                            'type': u'xsd:integer'}},
               'name': u'PermType'},
 u'PluginProperties': {'member': {u'plugin_property': {'sequence': True,
                                                       'type': u'PluginProperty'}},
                       'name': u'PluginProperties'},
 u'PluginProperty': {'member': {u'property': {'sequence': False,
                                              'type': u'xsd:string'},
                                u'value': {'sequence': False,
                                           'type': u'xsd:string'}},
                     'name': u'PluginProperty'},
 u'PolicyBasedForwardingRuleType': {'member': {u'direction': {'sequence': False,
                                                              'type': u'xsd:string'},
                                               u'dst_mac': {'sequence': False,
                                                            'type': u'xsd:string'},
                                               u'mpls_label': {'sequence': False,
                                                               'type': u'xsd:integer'},
                                               u'protocol': {'sequence': False,
                                                             'type': u'xsd:string'},
                                               u'service_chain_address': {'sequence': False,
                                                                          'type': u'xsd:string'},
                                               u'src_mac': {'sequence': False,
                                                            'type': u'xsd:string'},
                                               u'vlan_tag': {'sequence': False,
                                                             'type': u'xsd:integer'}},
                                    'name': u'PolicyBasedForwardingRuleType'},
 u'PolicyEntriesType': {'member': {u'policy_rule': {'sequence': True,
                                                    'type': u'PolicyRuleType'}},
                        'name': u'PolicyEntriesType'},
 u'PolicyRuleType': {'member': {u'action_list': {'sequence': False,
                                                 'type': u'ActionListType'},
                                u'application': {'sequence': True,
                                                 'type': u'xsd:string'},
                                u'direction': {'sequence': False,
                                               'type': u'xsd:string'},
                                u'dst_addresses': {'sequence': True,
                                                   'type': u'AddressType'},
                                u'dst_ports': {'sequence': True,
                                               'type': u'PortType'},
                                u'ethertype': {'sequence': False,
                                               'type': u'xsd:string'},
                                u'protocol': {'sequence': False,
                                              'type': u'xsd:string'},
                                u'rule_sequence': {'sequence': False,
                                                   'type': u'SequenceType'},
                                u'rule_uuid': {'sequence': False,
                                               'type': u'xsd:string'},
                                u'src_addresses': {'sequence': True,
                                                   'type': u'AddressType'},
                                u'src_ports': {'sequence': True,
                                               'type': u'PortType'}},
                     'name': u'PolicyRuleType'},
 u'PortType': {'member': {u'end_port': {'sequence': False,
                                        'type': u'xsd:integer'},
                          u'start_port': {'sequence': False,
                                          'type': u'xsd:integer'}},
               'name': u'PortType'},
 u'QuotaType': {'member': {u'access_control_list': {'sequence': False,
                                                    'type': u'xsd:integer'},
                           u'bgp_router': {'sequence': False,
                                           'type': u'xsd:integer'},
                           u'defaults': {'sequence': False,
                                         'type': u'xsd:integer'},
                           u'floating_ip': {'sequence': False,
                                            'type': u'xsd:integer'},
                           u'floating_ip_pool': {'sequence': False,
                                                 'type': u'xsd:integer'},
                           u'global_vrouter_config': {'sequence': False,
                                                      'type': u'xsd:integer'},
                           u'instance_ip': {'sequence': False,
                                            'type': u'xsd:integer'},
                           u'loadbalancer_healthmonitor': {'sequence': False,
                                                           'type': u'xsd:integer'},
                           u'loadbalancer_member': {'sequence': False,
                                                    'type': u'xsd:integer'},
                           u'loadbalancer_pool': {'sequence': False,
                                                  'type': u'xsd:integer'},
                           u'logical_router': {'sequence': False,
                                               'type': u'xsd:integer'},
                           u'network_ipam': {'sequence': False,
                                             'type': u'xsd:integer'},
                           u'network_policy': {'sequence': False,
                                               'type': u'xsd:integer'},
                           u'security_group': {'sequence': False,
                                               'type': u'xsd:integer'},
                           u'security_group_rule': {'sequence': False,
                                                    'type': u'xsd:integer'},
                           u'service_instance': {'sequence': False,
                                                 'type': u'xsd:integer'},
                           u'service_template': {'sequence': False,
                                                 'type': u'xsd:integer'},
                           u'subnet': {'sequence': False,
                                       'type': u'xsd:integer'},
                           u'virtual_DNS': {'sequence': False,
                                            'type': u'xsd:integer'},
                           u'virtual_DNS_record': {'sequence': False,
                                                   'type': u'xsd:integer'},
                           u'virtual_ip': {'sequence': False,
                                           'type': u'xsd:integer'},
                           u'virtual_machine_interface': {'sequence': False,
                                                          'type': u'xsd:integer'},
                           u'virtual_network': {'sequence': False,
                                                'type': u'xsd:integer'},
                           u'virtual_router': {'sequence': False,
                                               'type': u'xsd:integer'}},
                'name': u'QuotaType'},
 u'RouteTableType': {'member': {u'route': {'sequence': True,
                                           'type': u'RouteType'}},
                     'name': u'RouteTableType'},
 u'RouteTargetList': {'member': {u'route_target': {'sequence': True,
                                                   'type': u'xsd:string'}},
                      'name': u'RouteTargetList'},
 u'RouteType': {'member': {u'next_hop': {'sequence': False,
                                         'type': u'xsd:string'},
                           u'next_hop_type': {'sequence': False,
                                              'type': u'xsd:string'},
                           u'prefix': {'sequence': False,
                                       'type': u'xsd:string'}},
                'name': u'RouteType'},
 u'SNMPCredentials': {'member': {u'local_port': {'sequence': False,
                                                 'type': u'xsd:integer'},
                                 u'retries': {'sequence': False,
                                              'type': u'xsd:integer'},
                                 u'timeout': {'sequence': False,
                                              'type': u'xsd:integer'},
                                 u'v2_community': {'sequence': False,
                                                   'type': u'xsd:string'},
                                 u'v3_authentication_password': {'sequence': False,
                                                                 'type': u'xsd:string'},
                                 u'v3_authentication_protocol': {'sequence': False,
                                                                 'type': u'xsd:string'},
                                 u'v3_context': {'sequence': False,
                                                 'type': u'xsd:string'},
                                 u'v3_context_engine_id': {'sequence': False,
                                                           'type': u'xsd:string'},
                                 u'v3_engine_boots': {'sequence': False,
                                                      'type': u'xsd:integer'},
                                 u'v3_engine_id': {'sequence': False,
                                                   'type': u'xsd:string'},
                                 u'v3_engine_time': {'sequence': False,
                                                     'type': u'xsd:integer'},
                                 u'v3_privacy_password': {'sequence': False,
                                                          'type': u'xsd:string'},
                                 u'v3_privacy_protocol': {'sequence': False,
                                                          'type': u'xsd:string'},
                                 u'v3_security_engine_id': {'sequence': False,
                                                            'type': u'xsd:string'},
                                 u'v3_security_level': {'sequence': False,
                                                        'type': u'xsd:string'},
                                 u'v3_security_name': {'sequence': False,
                                                       'type': u'xsd:string'},
                                 u'version': {'sequence': False,
                                              'type': u'xsd:integer'}},
                      'name': u'SNMPCredentials'},
 u'SequenceType': {'member': {u'major': {'sequence': False,
                                         'type': u'xsd:integer'},
                              u'minor': {'sequence': False,
                                         'type': u'xsd:integer'}},
                   'name': u'SequenceType'},
 u'ServiceApplianceInterfaceType': {'member': {u'interface_type': {'sequence': False,
                                                                   'type': u'xsd:string'}},
                                    'name': u'ServiceApplianceInterfaceType'},
 u'ServiceInstanceInterfaceType': {'member': {u'ip_address': {'sequence': False,
                                                              'type': u'xsd:string'},
                                              u'static_routes': {'sequence': False,
                                                                 'type': u'RouteTableType'},
                                              u'virtual_network': {'sequence': False,
                                                                   'type': u'xsd:string'}},
                                   'name': u'ServiceInstanceInterfaceType'},
 u'ServiceInstanceType': {'member': {u'auto_policy': {'sequence': False,
                                                      'type': u'xsd:boolean'},
                                     u'availability_zone': {'sequence': False,
                                                            'type': u'xsd:string'},
                                     u'ha_mode': {'sequence': False,
                                                  'type': u'xsd:string'},
                                     u'interface_list': {'sequence': True,
                                                         'type': u'ServiceInstanceInterfaceType'},
                                     u'left_ip_address': {'sequence': False,
                                                          'type': u'xsd:string'},
                                     u'left_virtual_network': {'sequence': False,
                                                               'type': u'xsd:string'},
                                     u'management_virtual_network': {'sequence': False,
                                                                     'type': u'xsd:string'},
                                     u'right_ip_address': {'sequence': False,
                                                           'type': u'xsd:string'},
                                     u'right_virtual_network': {'sequence': False,
                                                                'type': u'xsd:string'},
                                     u'scale_out': {'sequence': False,
                                                    'type': u'ServiceScaleOutType'},
                                     u'virtual_router_id': {'sequence': False,
                                                            'type': u'xsd:string'}},
                          'name': u'ServiceInstanceType'},
 u'ServiceInstanceVirtualMachineInterfaceType': {'member': {u'instance_id': {'sequence': False,
                                                                             'type': u'xsd:integer'},
                                                            u'interface_type': {'sequence': False,
                                                                                'type': u'xsd:string'}},
                                                 'name': u'ServiceInstanceVirtualMachineInterfaceType'},
 u'ServiceScaleOutType': {'member': {u'auto_scale': {'sequence': False,
                                                     'type': u'xsd:boolean'},
                                     u'max_instances': {'sequence': False,
                                                        'type': u'xsd:integer'}},
                          'name': u'ServiceScaleOutType'},
 u'ServiceTemplateInterfaceType': {'member': {u'service_interface_type': {'sequence': False,
                                                                          'type': u'xsd:string'},
                                              u'shared_ip': {'sequence': False,
                                                             'type': u'xsd:boolean'},
                                              u'static_route_enable': {'sequence': False,
                                                                       'type': u'xsd:boolean'}},
                                   'name': u'ServiceTemplateInterfaceType'},
 u'ServiceTemplateType': {'member': {u'availability_zone_enable': {'sequence': False,
                                                                   'type': u'xsd:boolean'},
                                     u'flavor': {'sequence': False,
                                                 'type': u'xsd:string'},
                                     u'image_name': {'sequence': False,
                                                     'type': u'xsd:string'},
                                     u'instance_data': {'sequence': False,
                                                        'type': u'xsd:string'},
                                     u'interface_type': {'sequence': True,
                                                         'type': u'ServiceTemplateInterfaceType'},
                                     u'ordered_interfaces': {'sequence': False,
                                                             'type': u'xsd:boolean'},
                                     u'service_mode': {'sequence': False,
                                                       'type': u'xsd:string'},
                                     u'service_scaling': {'sequence': False,
                                                          'type': u'xsd:boolean'},
                                     u'service_type': {'sequence': False,
                                                       'type': u'xsd:string'},
                                     u'service_virtualization_type': {'sequence': False,
                                                                      'type': u'xsd:string'},
                                     u'vrouter_instance_type': {'sequence': False,
                                                                'type': u'xsd:string'}},
                          'name': u'ServiceTemplateType'},
 u'SubnetListType': {'member': {u'subnet': {'sequence': True,
                                            'type': u'SubnetType'}},
                     'name': u'SubnetListType'},
 u'SubnetType': {'member': {u'ip_prefix': {'sequence': False,
                                           'type': u'xsd:string'},
                            u'ip_prefix_len': {'sequence': False,
                                               'type': u'xsd:integer'}},
                 'name': u'SubnetType'},
 u'TimerType': {'member': {u'end_time': {'sequence': False,
                                         'type': u'xsd:dateTime'},
                           u'off_interval': {'sequence': False,
                                             'type': u'xsd:time'},
                           u'on_interval': {'sequence': False,
                                            'type': u'xsd:time'},
                           u'start_time': {'sequence': False,
                                           'type': u'xsd:dateTime'}},
                'name': u'TimerType'},
 u'UserCredentials': {'member': {u'password': {'sequence': False,
                                               'type': u'xsd:string'},
                                 u'username': {'sequence': False,
                                               'type': u'xsd:string'}},
                      'name': u'UserCredentials'},
 u'UuidType': {'member': {u'uuid_lslong': {'sequence': False,
                                           'type': u'xsd:unsignedLong'},
                          u'uuid_mslong': {'sequence': False,
                                           'type': u'xsd:unsignedLong'}},
               'name': u'UuidType'},
 u'VirtualDnsRecordType': {'member': {u'record_class': {'sequence': False,
                                                        'type': u'xsd:string'},
                                      u'record_data': {'sequence': False,
                                                       'type': u'xsd:string'},
                                      u'record_mx_preference': {'sequence': False,
                                                                'type': u'xsd:integer'},
                                      u'record_name': {'sequence': False,
                                                       'type': u'xsd:string'},
                                      u'record_ttl_seconds': {'sequence': False,
                                                              'type': u'xsd:integer'},
                                      u'record_type': {'sequence': False,
                                                       'type': u'xsd:string'}},
                           'name': u'VirtualDnsRecordType'},
 u'VirtualDnsType': {'member': {u'default_ttl_seconds': {'sequence': False,
                                                         'type': u'xsd:integer'},
                                u'domain_name': {'sequence': False,
                                                 'type': u'xsd:string'},
                                u'dynamic_records_from_client': {'sequence': False,
                                                                 'type': u'xsd:boolean'},
                                u'external_visible': {'sequence': False,
                                                      'type': u'xsd:boolean'},
                                u'floating_ip_record': {'sequence': False,
                                                        'type': u'xsd:string'},
                                u'next_virtual_DNS': {'sequence': False,
                                                      'type': u'xsd:string'},
                                u'record_order': {'sequence': False,
                                                  'type': u'xsd:string'},
                                u'reverse_resolution': {'sequence': False,
                                                        'type': u'xsd:boolean'}},
                     'name': u'VirtualDnsType'},
 u'VirtualIpType': {'member': {u'address': {'sequence': False,
                                            'type': u'xsd:string'},
                               u'admin_state': {'sequence': False,
                                                'type': u'xsd:boolean'},
                               u'connection_limit': {'sequence': False,
                                                     'type': u'xsd:integer'},
                               u'persistence_cookie_name': {'sequence': False,
                                                            'type': u'xsd:string'},
                               u'persistence_type': {'sequence': False,
                                                     'type': u'xsd:string'},
                               u'protocol': {'sequence': False,
                                             'type': u'xsd:string'},
                               u'protocol_port': {'sequence': False,
                                                  'type': u'xsd:integer'},
                               u'status': {'sequence': False,
                                           'type': u'xsd:string'},
                               u'status_description': {'sequence': False,
                                                       'type': u'xsd:string'},
                               u'subnet_id': {'sequence': False,
                                              'type': u'xsd:string'}},
                    'name': u'VirtualIpType'},
 u'VirtualMachineInterfacePropertiesType': {'member': {u'interface_mirror': {'sequence': False,
                                                                             'type': u'InterfaceMirrorType'},
                                                       u'local_preference': {'sequence': False,
                                                                             'type': u'xsd:integer'},
                                                       u'service_interface_type': {'sequence': False,
                                                                                   'type': u'xsd:string'},
                                                       u'sub_interface_vlan_tag': {'sequence': False,
                                                                                   'type': u'xsd:integer'}},
                                            'name': u'VirtualMachineInterfacePropertiesType'},
 u'VirtualNetworkPolicyType': {'member': {u'sequence': {'sequence': False,
                                                        'type': u'SequenceType'},
                                          u'timer': {'sequence': False,
                                                     'type': u'TimerType'}},
                               'name': u'VirtualNetworkPolicyType'},
 u'VirtualNetworkType': {'member': {u'allow_transit': {'sequence': False,
                                                       'type': u'xsd:boolean'},
                                    u'forwarding_mode': {'sequence': False,
                                                         'type': u'xsd:string'},
                                    u'network_id': {'sequence': False,
                                                    'type': u'xsd:integer'},
                                    u'rpf': {'sequence': False,
                                             'type': u'xsd:string'},
                                    u'vxlan_network_identifier': {'sequence': False,
                                                                  'type': u'xsd:integer'}},
                         'name': u'VirtualNetworkType'},
 u'VnSubnetsType': {'member': {u'host_routes': {'sequence': False,
                                                'type': u'RouteTableType'},
                               u'ipam_subnets': {'sequence': True,
                                                 'type': u'IpamSubnetType'}},
                    'name': u'VnSubnetsType'},
 u'VrfAssignRuleType': {'member': {u'ignore_acl': {'sequence': False,
                                                   'type': u'xsd:boolean'},
                                   u'match_condition': {'sequence': False,
                                                        'type': u'MatchConditionType'},
                                   u'routing_instance': {'sequence': False,
                                                         'type': u'xsd:string'},
                                   u'vlan_tag': {'sequence': False,
                                                 'type': u'xsd:integer'}},
                        'name': u'VrfAssignRuleType'},
 u'VrfAssignTableType': {'member': {u'vrf_assign_rule': {'sequence': True,
                                                         'type': u'VrfAssignRuleType'}},
                         'name': u'VrfAssignTableType'}}
